### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by hmaeta** [sacchie/satchi#11]
- E2E test
- non-E2E tests for main

**Comment by kigh-ota** [comment]
Electron アプリのE2Eテストは、知る限り [spectron](https://www.electronjs.org/spectron) 一択だと思う。
Cypress が対応しそうな[雰囲気](https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/)があったが、やめたみたい。
