### ISSUE TITLE
Electron-Main 間の通信を WebSocket 化する

### ISSUE THREAD

**Issue by kigh-ota** [sacchie/satchi#4]

**Comment by kigh-ota** [comment]
gRPC のストリームでも良いかも

**Comment by kigh-ota** [comment]
> gRPC のストリームでも良いかも

↑は雰囲気で書いていたので少し調べてみた。
結論から書くと、

- Main→Electronの片方向のストリーミングはOK
- Main↔Electronの双方向のストリーミングは、Renderer ProcessからはNGだが、Main ProcessからならOK

双方向の場合について補足。
まず、gRPC自体は双方向ストリーミングをサポートしている。https://grpc.io/docs/what-is-grpc/core-concepts/
ただし、ブラウザ（つまりRenderer Process）から使うためには[gRPC-Web](https://github.com/grpc/grpc-web)という仕組みを使う必要があり、これは双方向ストリーミングをサポートしていない。https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md

**Comment by hmaeta** [comment]
websocket化は完了
